// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as ClientOptions, TDataShape } from '@hey-api/client-fetch'

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> =
  ClientOptions<TData, ThrowOnError>
  & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
};
